apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secret
  namespace: togglemaster
type: Opaque
stringData:
  DATABASE_URL: "postgresql://USER:PASSWORD@RDS_ENDPOINT:5432/flags?sslmode=require"
