name: auth-service
on:
  pull_request: { paths: ['services/auth-service/**', '.github/workflows/**'] }
  push: { branches: [main], paths: ['services/auth-service/**', '.github/workflows/**'] }
jobs:
  devsecops:
    uses: ./.github/workflows/reusable-devsecops.yml
    with: { service: auth-service, language: go }
    secrets: inherit

